module.exports = {
	content: ['./src/**/*.{js,jsx,ts,tsx}'],
	theme: {
		extend: {
			screens: {
				sm: '600px', // Small screens and up
				md: '768px', // Medium screens and up
				lg: '1024px', // Large screens and up
			},
		},
	},
	//thanks tailwind
	safelist: [
		'text-ctp-rosewater',
		'text-ctp-flamingo',
		'text-ctp-pink',
		'text-ctp-mauve',
		'text-ctp-red',
		'text-ctp-maroon',
		'text-ctp-peach',
		'text-ctp-yellow',
		'text-ctp-green',
		'text-ctp-teal',
		'text-ctp-sky',
		'text-ctp-sapphire',
		'text-ctp-blue',
		'text-ctp-lavender',
		'fill-ctp-rosewater',
		'fill-ctp-flamingo',
		'fill-ctp-pink',
		'fill-ctp-mauve',
		'fill-ctp-red',
		'fill-ctp-maroon',
		'fill-ctp-peach',
		'fill-ctp-yellow',
		'fill-ctp-green',
		'fill-ctp-teal',
		'fill-ctp-sky',
		'fill-ctp-sapphire',
		'fill-ctp-blue',
		'fill-ctp-lavender',
		'to-ctp-rosewater',
		'to-ctp-flamingo',
		'to-ctp-pink',
		'to-ctp-mauve',
		'to-ctp-red',
		'to-ctp-maroon',
		'to-ctp-peach',
		'to-ctp-yellow',
		'to-ctp-green',
		'to-ctp-teal',
		'to-ctp-sky',
		'to-ctp-sapphire',
		'to-ctp-blue',
		'to-ctp-lavender',
		'from-ctp-rosewater',
		'from-ctp-flamingo',
		'from-ctp-pink',
		'from-ctp-mauve',
		'from-ctp-red',
		'from-ctp-maroon',
		'from-ctp-peach',
		'from-ctp-yellow',
		'from-ctp-green',
		'from-ctp-teal',
		'from-ctp-sky',
		'from-ctp-sapphire',
		'from-ctp-blue',
		'from-ctp-lavender',
		'bg-ctp-rosewater',
		'bg-ctp-flamingo',
		'bg-ctp-pink',
		'bg-ctp-mauve',
		'bg-ctp-red',
		'bg-ctp-maroon',
		'bg-ctp-peach',
		'bg-ctp-yellow',
		'bg-ctp-green',
		'bg-ctp-teal',
		'bg-ctp-sky',
		'bg-ctp-sapphire',
		'bg-ctp-blue',
		'bg-ctp-lavender',
		'border-ctp-rosewater',
		'border-ctp-flamingo',
		'border-ctp-pink',
		'border-ctp-mauve',
		'border-ctp-red',
		'border-ctp-maroon',
		'border-ctp-peach',
		'border-ctp-yellow',
		'border-ctp-green',
		'border-ctp-teal',
		'border-ctp-sky',
		'border-ctp-sapphire',
		'border-ctp-blue',
		'border-ctp-lavender',
		'ring-ctp-rosewater',
		'ring-ctp-flamingo',
		'ring-ctp-pink',
		'ring-ctp-mauve',
		'ring-ctp-red',
		'ring-ctp-maroon',
		'ring-ctp-peach',
		'ring-ctp-yellow',
		'ring-ctp-green',
		'ring-ctp-teal',
		'ring-ctp-sky',
		'ring-ctp-sapphire',
		'ring-ctp-blue',
		'ring-ctp-lavender',
	],
	plugins: [
		require('@catppuccin/tailwindcss')({
			prefix: 'ctp',
			defaultFlavour: 'mocha',
		}),
	],
};
